### ISSUE TITLE
Win7这里运行的时候出错，不知道缺了什么东西

### ISSUE THREAD

**Issue by winsion** [xksoft/OcrHelper#6]
![Snipaste_2023-04-06_16-34-15](https://user-images.githubusercontent.com/6326075/230322979-95097066-2b48-4f42-8ebe-69804c73fb54.jpg)
------------------------------------------------------------错误如下：

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.DllNotFoundException: Dll was not found.
   at PaddleOCRSharp.PaddleOCREngine.Initialize(String det_infer, String cls_infer, String rec_infer, String keys, OCRParameter parameter)
   at PaddleOCRSharp.PaddleOCREngine..ctor(OCRModelConfig config, OCRParameter parameter)
   at OcrHelper.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
OcrHelper
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
PaddleOCRSharp
    程序集版本:2.3.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.FileVersionInfo
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Resources.Extensions
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------

************** JIT 调试 **************

**Comment by louliangsheng** [comment]
我也遇到了同样的问题

**Comment by xiakexiaoyi** [comment]
这种大概率是系统缺少c++运行库，装个全家桶应该就可以了，试试看
http://soft.360.cn/static/baoku/info_7_0/softinfo_104698064.html
